### ISSUE TITLE
Consider dropping inclusion of for/else

### ISSUE THREAD

**Issue by bbrandt** [tukkek/notablepython#4]
https://github.com/tukkek/notablepython#unconventional-else-blocks

I know this is not everyone's opinion, but in Brett Slatkin's book, "Effective Python", he recommends in Item #12 to "Avoid else Blocks After for and while loops", arguing that the results in some cases can be unexpected.  The argument made a lot of sense to me.  

Another fellow has a blog article about it here as well:
https://python-notes.curiousefficiency.org/en/latest/python_concepts/break_else.html

Obviously, someone thinks its a good idea, or it wouldn't be in the language.  What do you think?

**Comment by tukkek** [comment]
I personally think it's useful although I agree the semantics are confusing. I guess I'll defer to Guido on this one - if he thinks it's OK to have in the language, who am I to say otherwise? :) I think it's a reasonable yet imperfect way to deal with Python's lack of loop labels (`updating: for d in data` ... `continue updating`).

If you can find me a bite-sized sentence or two from the book warning about using for-else, I will gladly quote it on the appropriate section! The article you sent is very relevant but not very straightforward, I'm afraid, otherwise I'd link it instead...

Thanks for the feedback!
